language: go

go:
  - 1.4

before_install:
  - sudo pip install codecov

install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/gin-gonic/gin

script:
  - ./coverage.sh

after_success:
  - codecov

